apiVersion: v1
kind: Service
metadata:
  name: ms-participantes
  labels:
    app: ms-participantes
spec:
  type: NodePort
  selector:
    app: ms-participantes
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
    nodePort: 30091