apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-participantes-deployment
  labels:
    app: ms-participantes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-participantes
  template:
    metadata:
      labels:
        app: ms-participantes
    spec:
      containers:
        - name: ms-participantes
          image: anthonyponte/ms-participantes:1.0.2
          args:
            - "--spring.config.additional-location=file:/config/"
          ports:
            - containerPort: 9091
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9091
            initialDelaySeconds: 400
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9091
            initialDelaySeconds: 105
            periodSeconds: 10
            timeoutSeconds: 10
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secret
                  key: DB_PASSWORD
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "200m"
              memory: "600Mi"
          volumeMounts:
            - name: ms-participantes-volume
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: ms-participantes-volume
          configMap:
            name: ms-participantes-configmap
            items:
              - key: application.yml
                path: application.yml